export const constants = {
    REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
    REGISTER_SUCCESS_REQUEST: "USERS_REGISTER_SUCCESS",
    REGISTER_FAILURE_REQUEST: "USERS_REGISTER_FAILURE",

    REGISTER_CONFIRM_REQUEST: "USERS_REGISTER_CONFIRM_REQUEST",
    REGISTER_CONFIRM_SUCCESS: "USERS_REGISTER_CONFIRM_SUCCESS",
    REGISTER_CONFIRM_FAILURE: "USERS_REGISTER_CONFIRM_FAILURE",

    LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
    LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
    LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

    //2FA authentication
    LOGIN_SECURITY_REQUEST: "USER_LOGIN_SECURITY_REQUEST",
    LOGIN_SECURITY_SUCCESS: "USER_LOGIN_SECURITY_SUCCESS",
    LOGIN_SECURITY_FAILURE: "USER_LOGIN_SECURITY_FAILURE",

    LOGOUT_REQUEST: "USERS_LOGOUT_REQUEST",

    RESET_PASSWORD_REQUEST: "USERS_RESET_PASSWORD_REQUEST",
    RESET_PASSWORD_SUCCESS: "USERS_RESET_PASSWORD_SUCCESS",
    RESET_PASSWORD_FAILURE: "USERS_RESET_PASSWORD_FAILURE",

    RESET_PASSWORD_CONFIRM_REQUEST: "USERS_RESET_PASSWORD_CONFIRM_REQUEST",
    RESET_PASSWORD_CONFIRM_SUCCESS: "USERS_RESET_PASSWORD_CONFIRM_SUCCESS",
    RESET_PASSWORD_CONFIRM_FAILURE: "USERS_RESET_PASSWORD_CONFIRM_FAILURE",

};